apiVersion: v1
kind: PersistentVolume
metadata:
  name: nailed-db
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/misc/nailed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nailed-db
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: nailed-db
